# ICE Outcomes: Data Exploration & Cleaning

### 2012 - 2023 deportation data
---

In [1]:
# import modules
import pandas as pd

In [13]:
# 2012 detentions
detentions_12 = pd.read_excel("../data/ice_release_2011to2023/2023-ICFO_42034_Detentions_FY12_LESA-STU_FINAL-Redacted_raw.xlsx", header=5)
detentions_12.head()

,Detention ID,Case ID,Subject ID,Stay Book In Date,Detention Book In Date,Detention Facility,Detention Facility Code,Detention Book Out Date,Detention Release Reason,Stay Book Out Date,...,Case Category,Final Order Yes No,Final Order Date,Departed Date,Departure Country,Case Threat Level,Charge,Charge Code,Charge Section Code,Anonymized Identifier
0,(b)(6)(b)(7)(c),(b)(6)(b)(7)(c),(b)(6)(b)(7)(c),2012-08-09,2012-08-09,LAREDO PROCESSING CENTER,LRDICDF,2012-09-15,Transferred,2012-10-24,...,[8G] Expedited Removal - Credible Fear Referral,NO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,00001ba710a6686c93329ecb68f6d3c2c8585083
1,(b)(6)(b)(7)(c),(b)(6)(b)(7)(c),(b)(6)(b)(7)(c),2012-08-09,2012-09-15,T DON HUTTO DETENTION CENTER,CCAHUTX,2012-10-24,Order of recognizance,2012-10-24,...,[8G] Expedited Removal - Credible Fear Referral,NO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,00001ba710a6686c93329ecb68f6d3c2c8585083
2,(b)(6)(b)(7)(c),(b)(6)(b)(7)(c),(b)(6)(b)(7)(c),2012-08-28,2012-08-28,BALTIMORE HOLD ROOM,BALHOLD,2012-08-28,Transferred,2012-11-19,...,[3] Deportable - Administratively Final Order,YES,2013-08-09 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,00001ed059f30ad45f361ac3e86087cc9854a1fb
3,(b)(6)(b)(7)(c),(b)(6)(b)(7)(c),(b)(6)(b)(7)(c),2012-08-28,2012-08-28,HOWARD COUNTY DET CNTR,HOWARMD,2012-11-19,ATD - Alternatives to Detention,2012-11-19,...,[3] Deportable - Administratively Final Order,YES,2013-08-09 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,00001ed059f30ad45f361ac3e86087cc9854a1fb
4,(b)(6)(b)(7)(c),(b)(6)(b)(7)(c),(b)(6)(b)(7)(c),2012-04-26,2012-04-26,FLORENCE STAGING FACILITY,FSF,2012-04-26,Transferred,2012-04-27,...,[8F] Expedited Removal,YES,2012-04-25 00:00:00,2012-04-27 00:00:00,MEXICO,NaN,IMMIGRANT WITHOUT AN IMMIGRANT VISA,I7A1,212a7AiI,000048a302c4e394aa8544d8555ca2ed26b8d34a

### Tables from 2023 - 2025 deportation data
---

In [ ]:
# arrests 2023 to 2025 df
arrests_23_25 = pd.read_excel("../data/ice_release_2023to2025/ERO Admin Arrests_LESA-STU-FINAL Release.xlsx", header=6)
arrests_23_25.head()

,Apprehension Date,Apprehension State,Apprehension County,Apprehension AOR,Final Program,Final Program Group,Apprehension Method,Apprehension Criminality,Case Status,Case Category,...,Final Order Date,Birth Date,Birth Year,Citizenship Country,Gender,Apprehension Site Landmark,Alien File Number,EID Case ID,EID Subject ID,Unique Identifier
0,2023-09-23 09:01:00,NaN,NaN,Atlanta Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Local Incarceration,1 Convicted Criminal,8-Excluded/Removed - Inadmissibility,[8C] Excludable / Inadmissible - Administrativ...,...,2023-10-16,"(b)(6), (b)(7)(c)",1963.0,MEXICO,Male,NC DEPT OF CORRECTIONS FACILITY,"(b)(6), (b)(7)(c)","(b)(6), (b)(7)(c) (b)(7)(e)","(b)(6), (b)(7)(c) (b)(7)(e)",00007cb10d7edd5e97cbefad22016c1679d98343
1,2023-11-09 11:06:00,NaN,NaN,San Francisco Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Federal Incarceration,1 Convicted Criminal,8-Excluded/Removed - Inadmissibility,[16] Reinstated Final Order,...,2017-03-08,"(b)(6), (b)(7)(c)",1996.0,HONDURAS,Male,"SFR GENERAL AREA, NON-SPECIFIC","(b)(6), (b)(7)(c)","(b)(6), (b)(7)(c) (b)(7)(e)","(b)(6), (b)(7)(c) (b)(7)(e)",00008df187d556536d9799c5a3e889cbca52ae48
2,2025-09-11 11:58:34,CALIFORNIA,NaN,San Francisco Area of Responsibility,ERO Criminal Alien Program,ICE,Custodial Arrest,1 Convicted Criminal,8-Excluded/Removed - Inadmissibility,[16] Reinstated Final Order,...,2024-09-21,"(b)(6), (b)(7)(c)",1996.0,HONDURAS,Male,"SFR GENERAL AREA, NON-SPECIFIC","(b)(6), (b)(7)(c)","(b)(6), (b)(7)(c) (b)(7)(e)","(b)(6), (b)(7)(c) (b)(7)(e)",00008df187d556536d9799c5a3e889cbca52ae48
3,2025-07-08 11:06:36,NaN,NaN,El Paso Area of Responsibility,Juvenile,ICE,Patrol Border,1 Convicted Criminal,8-Excluded/Removed - Inadmissibility,[16] Reinstated Final Order,...,2025-07-08,"(b)(6), (b)(7)(c)",1982.0,GUATEMALA,Female,HERRING ROAD TO WEST DAVIS TREE LINE,"(b)(6), (b)(7)(c)","(b)(6), (b)(7)(c) (b)(7)(e)","(b)(6), (b)(7)(c) (b)(7)(e)",0000a20d6fc6f1422724c45928b989a9915ce48e
4,2025-09-23 13:22:06,TEXAS,NaN,El Paso Area of Responsibility,ERO Criminal Alien Program,ICE,Custodial Arrest,1 Convicted Criminal,8-Excluded/Removed - Inadmissibility,[16] Reinstated Final Order,...,2025-07-08,"(b)(6), (b)(7)(c)",1982.0,GUATEMALA,Female,"EPC GENERAL AREA, NON-SPECIFIC","(b)(6), (b)(7)(c)","(b)(6), (b)(7)(c) (b)(7)(e)","(b)(6), (b)(7)(c) (b)(7)(e)",0000a20d6fc6f1422724c45928b989a9915ce48e

In [ ]:
# arrests 2023 to 2025 information
arrests_23_25.columns

Index(['Apprehension Date', 'Apprehension State', 'Apprehension County',
       'Apprehension AOR', 'Final Program', 'Final Program Group',
       'Apprehension Method', 'Apprehension Criminality', 'Case Status',
       'Case Category', 'Departed Date', 'Departure Country',
       'Final Order Yes No', 'Final Order Date', 'Birth Date', 'Birth Year',
       'Citizenship Country', 'Gender', 'Apprehension Site Landmark',
       'Alien File Number', 'EID Case ID', 'EID Subject ID',
       'Unique Identifier'],
      dtype='str')

In [ ]:
# detainers 2023 to 2025 df
detainers_23_25 = pd.read_excel("../data/ice_release_2023to2025/ERO Detainers_LESA-STU_FINAL Release.xlsx", header=6)
detainers_23_25.head()

,Detainer Prepare Date,Facility State,Facility AOR,Port of Departure,Departure Country,Departed Date,Case Status,Detainer Prepared Criminality,Detention Facility,Detention Facility Code,...,Final Order Yes No,Federal Interest Yes No,Resume Custody Yes No,Detainer Lift Reason,Detainer Type,Alien File Number,EID Case ID,EID Subject ID,EID DTA ID,Unique Identifier
0,2025-09-18,NEW YORK,New York City Area of Responsibility,NaN,NaN,NaT,ACTIVE,2 Pending Criminal Charges,QUEENS CENTRAL BOOKING,QUEENNY,...,NO,NaN,NO,Detainer Declined by LEA,I247A - Immigration Detainer - Notice of Actio...,"(b)(6), (b)(7)(c)","(b)(6), (b)(7)(c) (b)(7)(e)","(b)(6), (b)(7)(c) (b)(7)(e)","(b)(6), (b)(7)(c) (b)(7)(e)",000038b86db2d5a0689a047fe3329f5f9f5336f0
1,2023-10-12,CALIFORNIA,San Francisco Area of Responsibility,"SAN ANTONIO, TX, POE",HONDURAS,2023-12-18,8-Excluded/Removed - Inadmissibility,2 Pending Criminal Charges,"US MARSHALS, N.DIST.CA",USMNDCA,...,NO,NaN,NO,Booked into Detention,I247A - Immigration Detainer - Immigration Det...,"(b)(6), (b)(7)(c)","(b)(6), (b)(7)(c) (b)(7)(e)","(b)(6), (b)(7)(c) (b)(7)(e)","(b)(6), (b)(7)(c) (b)(7)(e)",00008df187d556536d9799c5a3e889cbca52ae48
2,2025-04-05,CALIFORNIA,San Francisco Area of Responsibility,"EL PASO, TX, POE",HONDURAS,2025-09-16,8-Excluded/Removed - Inadmissibility,2 Pending Criminal Charges,"US MARSHALS, N.DIST.CA",USMNDCA,...,NO,NaN,NO,Booked into Detention,I247A - Immigration Detainer - Immigration Det...,"(b)(6), (b)(7)(c)","(b)(6), (b)(7)(c) (b)(7)(e)","(b)(6), (b)(7)(c) (b)(7)(e)","(b)(6), (b)(7)(c) (b)(7)(e)",00008df187d556536d9799c5a3e889cbca52ae48
3,2025-09-23,TEXAS,NaN,NaN,NaN,NaT,NaN,2 Pending Criminal Charges,HARRIS COUNTY JAIL,HARISTX,...,NaN,NaN,NO,NaN,I247A - Immigration Detainer - Notice of Actio...,"(b)(6), (b)(7)(c)",NaN,"(b)(6), (b)(7)(c) (b)(7)(e)","(b)(6), (b)(7)(c) (b)(7)(e)",0000c09a82c3b50088121030ee7346951bce6076
4,2024-12-16,ILLINOIS,Chicago Area of Responsibility,NaN,NaN,NaT,ACTIVE,1 Convicted Criminal,PINCKNEYVILLE CORRECTIONAL CENTER,ILPICKN,...,NO,NaN,NO,NaN,I247A - Immigration Detainer - Immigration Det...,"(b)(6), (b)(7)(c)","(b)(6), (b)(7)(c) (b)(7)(e)","(b)(6), (b)(7)(c) (b)(7)(e)","(b)(6), (b)(7)(c) (b)(7)(e)",0000ef00672324bf7fd29a120693b382a340da36

In [14]:
detainers_23_25.columns

Index(['Detainer Prepare Date', 'Facility State', 'Facility AOR',
       'Port of Departure', 'Departure Country', 'Departed Date',
       'Case Status', 'Detainer Prepared Criminality', 'Detention Facility',
       'Detention Facility Code', 'Facility City',
       'Detainer Prep Threat Level', 'Gender', 'Citizenship Country',
       'Birth Country', 'Birth Date', 'Birth Year', 'Entry Status',
       'Most Serious Conviction (MSC) Charge', 'MSC Sentence Days',
       'MSC Sentence Months', 'MSC Sentence Years', 'MSC Charge Code',
       'MSC Charge Date', 'MSC Conviction Date', 'Felon',
       'Processing Disposition', 'Case Category', 'Final Program',
       'Time of Apprehension Case Category',
       'Time of Apprehension Current Program', 'Apprehension Method',
       'Case Final Order Yes No', 'Final Order Date', 'Apprehension Date',
       'Entry Date', 'Prior Felony Yes No', 'Multiple Prior MISD Yes No',
       'Violent Misdemeanor Yes No', 'Illegal Entry Yes No',
       'Illegal Reentry Yes No', 'Immigration Fraud Yes No',
       'Significant Risk Yes No', 'Other Removal Reason Yes No',
       'Other Removal Reason', 'Criminal Street Gang Yes No',
       'Aggravated Felony Yes No', 'Deportation Ordered Yes No',
       'Order to Show Cause Served Yes No', 'Order to Show Cause Served Date',
       'Biometric Match Yes No', 'Statements Made Yes No',
       'Unlawful Attempt Yes No', 'Unlawful Entry Yes No', 'Visa Yes No',
       'Final Order Yes No', 'Federal Interest Yes No',
       'Resume Custody Yes No', 'Detainer Lift Reason', 'Detainer Type',
       'Alien File Number', 'EID Case ID', 'EID Subject ID', 'EID DTA ID',
       'Unique Identifier'],
      dtype='str')

In [ ]:
# detentions 2023 to 2025 df
detentions_23_25 = pd.read_excel("../data/ice_release_2023to2025/ICE Detentions_LESA-STU_FINAL Release.xlsx", header=6)
detentions_23_25.head()

,Stay Book In Date Time,Book In Date Time,Detention Facility,Detention Facility Code,Detention Book Out Date Time,Stay Book Out Date Time,Detention Release Reason,Stay Book Out Date,Stay Release Reason,Religion,...,Departure Country,Initial Bond Set Amount,Citizenship Country,Final Program,Most Serious Conviction (MSC) Charge Code,MSC Charge,Alien File Number,EID Case ID,EID Subject ID,Unique Identifier
0,2023-05-10 07:50:00,2023-05-10 07:50:00,ELOY FED CTR FACILITY (CORE CIVIC),EAZ,2023-09-22 09:40:00,2023-09-22 09:40:00,Order of supervision,2023-09-22,Order of supervision,NaN,...,NaN,NaN,"CHINA, PEOPLES REPUBLIC OF",Border Patrol,NaN,NaN,"(b)(6), (b)(7)(c)","(b)(6), (b)(7)(c) (b)(7)(e)","(b)(6), (b)(7)(c) (b)(7)(e)",ffffd157920add678ab0dae4c253d83008311c10
1,2024-05-25 03:55:00,2024-06-21 20:53:00,MONTGOMERY PROCESSING CTR,MTGPCTX,2024-07-25 13:41:00,2024-07-30 11:23:00,Transferred,2024-07-30,Removed,NaN,...,GUATEMALA,NaN,GUATEMALA,Border Patrol,NaN,NaN,"(b)(6), (b)(7)(c)","(b)(6), (b)(7)(c) (b)(7)(e)","(b)(6), (b)(7)(c) (b)(7)(e)",ffffcb226a521273cf595148b247b0021c162435
2,2024-05-25 03:55:00,2024-07-25 13:46:00,ALEXANDRIA STAGING FACILITY,JENATLA,2024-07-30 11:23:00,2024-07-30 11:23:00,Removed,2024-07-30,Removed,NaN,...,GUATEMALA,NaN,GUATEMALA,Border Patrol,NaN,NaN,"(b)(6), (b)(7)(c)","(b)(6), (b)(7)(c) (b)(7)(e)","(b)(6), (b)(7)(c) (b)(7)(e)",ffffcb226a521273cf595148b247b0021c162435
3,2024-02-07 16:30:00,2024-02-07 16:30:00,ELOY FED CTR FACILITY (CORE CIVIC),EAZ,2024-04-17 01:59:00,2024-05-01 12:26:00,Transferred,2024-05-01,Removed,NaN,...,COLOMBIA,NaN,COLOMBIA,Border Patrol,NaN,NaN,"(b)(6), (b)(7)(c)","(b)(6), (b)(7)(c) (b)(7)(e)","(b)(6), (b)(7)(c) (b)(7)(e)",ffff33de6105ce59de35e99e3522e1cc1a737dda
4,2024-02-07 16:30:00,2024-04-17 16:02:00,JACKSON PARISH CORRECTIONAL CENTER,JKPCCLA,2024-05-01 12:26:00,2024-05-01 12:26:00,Removed,2024-05-01,Removed,NaN,...,COLOMBIA,NaN,COLOMBIA,Border Patrol,NaN,NaN,"(b)(6), (b)(7)(c)","(b)(6), (b)(7)(c) (b)(7)(e)","(b)(6), (b)(7)(c) (b)(7)(e)",ffff33de6105ce59de35e99e3522e1cc1a737dda

In [17]:
detentions_23_25.columns

Index(['Stay Book In Date Time', 'Book In Date Time', 'Detention Facility',
       'Detention Facility Code', 'Detention Book Out Date Time',
       'Stay Book Out Date Time', 'Detention Release Reason',
       'Stay Book Out Date', 'Stay Release Reason', 'Religion', 'Gender',
       'Marital Status', 'Birth Date', 'Birth Year', 'Ethnicity',
       'Entry Status', 'Felon', 'Bond Posted Date', 'Bond Posted Amount',
       'Case Status', 'Case Category', 'Final Order Yes No',
       'Final Order Date', 'Case Threat Level', 'Book In Criminality',
       'Final Charge', 'Departed Date', 'Departure Country',
       'Initial Bond Set Amount', 'Citizenship Country', 'Final Program',
       'Most Serious Conviction (MSC) Charge Code', 'MSC Charge',
       'Alien File Number', 'EID Case ID', 'EID Subject ID',
       'Unique Identifier'],
      dtype='str')